### ISSUE TITLE
Naming convention: Jobs

### ISSUE THREAD

**Issue by slremy** [ibm-cloud-docs/codeengine#10]
I'm not sure this is a popularly held view.. but I normally think of deploying workers.. and workers are the entities which can do jobs.

https://cloud.ibm.com/docs/codeengine?topic=codeengine-job-deploy

Thus in this whole metaphor, I create and deploy a worker (not a job)... the job is generated by the enduser. With the existing metaphor when I first heard of creating jobs and applications, it was not immediately clear to me how they were related. I was also curious why I would need to "Plan a container image" for jobs as if I was pre-packaging jobs to be done before they existed.

I wonder if this use of job is really coming from k8 and other places.. so it may be a lost cause to hope for change across all of these projects. 
Reading the documentation did clarify these things eventually, but just wanted share how my mental model was impacted by the naming convention.

**Comment by kersten1** [comment]
Thank you for this perspective! We pulled the content down into an internal issue. We are looking to create a topic about the underlying technologies for Code Engine, which should help with this confusion.

With Code engine, jobs are just batch jobs. They aren't really workers although they use workers as part of the underlying technology, since the underlying technology is Kubernetes.
