### ISSUE TITLE
CLI didn't provide the full name of the jobrun

### ISSUE THREAD

**Issue by slremy** [ibm-cloud-docs/codeengine#14]
I'm running ibmcloud with the code-engine plugin
version:  v1.19.0  
commit:   9e8ca698d7e141fa2d83fa45f03ea3a6b8e93aa5  

I connected to my project using `ibmcloud code-engine project select --name MYPROJECT --kubectl` 

```
user$ kubectl get pods
NAME                                                     READY   STATUS      RESTARTS   AGE
8e33bf3d-27ed-4faf-a5ae-7bdf0ccaec54-string-0-0          0/1     Completed   0          2m28s
```
vs
```
user$ ibmcloud ce jobrun list
Name                                         Requested  Pending  Running  Failed  Succeeded  Unknown  Age  
8e33bf3d-27ed-4faf-a5ae-7bdf0ccaec54-string  0          0        0        0       1          0        25s  
```

I tried to see the logs for the jobrun, but was only able to get the name of the instance from the first command above, while the second failed.

```
user$ ibmcloud ce jobrun logs 47fab72c-39ca-4238-b459-7eff38408724-string 
Getting logs for job run instance '8e33bf3d-27ed-4faf-a5ae-7bdf0ccaec54-string'...
FAILED
Failed to get job run instance '8e33bf3d-27ed-4faf-a5ae-7bdf0ccaec54-string'.

user$ ibmcloud ce jobrun logs --instance 8e33bf3d-27ed-4faf-a5ae-7bdf0ccaec54-string-0-0
Getting logs for job run instance '8e33bf3d-27ed-4faf-a5ae-7bdf0ccaec54-string-0-0'...
OK

8e33bf3d-27ed-4faf-a5ae-7bdf0ccaec54-string-0-0/job:    
hello  
```
Is this the intended behavior?

**Comment by kersten1** [comment]
Hello, your first command do not include the `--instance` option. Can you confirm that it fails when you run `ibmcloud ce jobrun logs --instance 47fab72c-39ca-4238-b459-7eff38408724-string`?

**Comment by slremy** [comment]
Hello! I checked again with a new job, and yes for me it does fail.

**Comment by rboykin** [comment]
The original command should have failed since you did not have a name for the jobrun:
This `ibmcloud ce jobrun logs 47fab72c-39ca-4238-b459-7eff38408724-string` should be this
`ibmcloud ce jobrun logs -n 47fab72c-39ca-4238-b459-7eff38408724-string`

The jobrun logs command can work against either the entire jobrun (which can have many instances) or against a single instance. 
- For the former, Use the syntax I show from above `ibmcloud ce jobrun logs -n <jobrun name>`. This will show logs for each instance of the jobrun. 
- For the latter, use `ibmcloud ce jobrun logs -i <jobrun-instance-name>`. This will show logs for a single instance of the jobrun. You can retrieve the instances of the jobrun using `ibmcloud ce jobrun get -n <jobrun name>`

Both options are supported and are working as expected.

**Comment by rboykin** [comment]
Also, it's always worth ensuring you are running using the latest Code Engine CLI plugin:
```
ibmcloud plugin update
```

**Comment by slremy** [comment]
@rboykin's comment pointed to my deficiency and it's rooted in jobrun name vs jobruninstance name.
```
  --instance, -i value            The name of a specific job run instance. Run 'ibmcloud ce jobrun get' to retrieve the instances.  
  --jobrun, -j, --name, -n value  Display the logs of all the instances of the specified job run. 
```

Thanks all
